### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by ranhaogong** [geospatial-lab/APC2Mesh#2]
Thanks for your excellent work!
Could you illustrate a thorough explanation of how to run the code.
Additionally, I noticed that the [building3d](https://building3d.ucalgary.ca/index.php) contains only dataset of the Tallinn city, where can I get datasets of other cities?
Looking forward to hearing from you!

**Comment by Timeless-H** [comment]
@ranhaogong I have updated the readme.md file of this repo. I hope it offers you some insight on how to navigate this repo.
